from PySide6.QtCore import Qt

full_key_map = {
    Qt.Key.Key_Escape: "Escape",
    Qt.Key.Key_Tab: "Tab",
    Qt.Key.Key_Backtab: "Backtab",
    Qt.Key.Key_Backspace: "Backspace",
    Qt.Key.Key_Return: "Return",
    Qt.Key.Key_Enter: "Enter",
    Qt.Key.Key_Insert: "Insert",
    Qt.Key.Key_Delete: "Delete",
    Qt.Key.Key_Pause: "Pause",
    Qt.Key.Key_Print: "Print",
    Qt.Key.Key_SysReq: "SysReq",
    Qt.Key.Key_Clear: "Clear",
    Qt.Key.Key_Home: "Home",
    Qt.Key.Key_End: "End",
    Qt.Key.Key_Left: "Left",
    Qt.Key.Key_Up: "Up",
    Qt.Key.Key_Right: "Right",
    Qt.Key.Key_Down: "Down",
    Qt.Key.Key_PageUp: "PageUp",
    Qt.Key.Key_PageDown: "PageDown",
    Qt.Key.Key_Shift: "Shift",
    Qt.Key.Key_Control: "Control",
    Qt.Key.Key_Meta: "Meta",
    Qt.Key.Key_Alt: "Alt",
    Qt.Key.Key_CapsLock: "CapsLock",
    Qt.Key.Key_NumLock: "NumLock",
    Qt.Key.Key_ScrollLock: "ScrollLock",
    Qt.Key.Key_F1: "F1",
    Qt.Key.Key_F2: "F2",
    Qt.Key.Key_F3: "F3",
    Qt.Key.Key_F4: "F4",
    Qt.Key.Key_F5: "F5",
    Qt.Key.Key_F6: "F6",
    Qt.Key.Key_F7: "F7",
    Qt.Key.Key_F8: "F8",
    Qt.Key.Key_F9: "F9",
    Qt.Key.Key_F10: "F10",
    Qt.Key.Key_F11: "F11",
    Qt.Key.Key_F12: "F12",
    Qt.Key.Key_Space: "Space",
    Qt.Key.Key_Exclam: "!",
    Qt.Key.Key_QuoteDbl: "\"",
    Qt.Key.Key_NumberSign: "#",
    Qt.Key.Key_Dollar: "$",
    Qt.Key.Key_Percent: "%",
    Qt.Key.Key_Ampersand: "&",
    Qt.Key.Key_Apostrophe: "'",
    Qt.Key.Key_ParenLeft: "(",
    Qt.Key.Key_ParenRight: ")",
    Qt.Key.Key_Asterisk: "*",
    Qt.Key.Key_Plus: "+",
    Qt.Key.Key_Comma: ",",
    Qt.Key.Key_Minus: "-",
    Qt.Key.Key_Period: ".",
    Qt.Key.Key_Slash: "/",
    Qt.Key.Key_0: "0",
    Qt.Key.Key_1: "1",
    Qt.Key.Key_2: "2",
    Qt.Key.Key_3: "3",
    Qt.Key.Key_4: "4",
    Qt.Key.Key_5: "5",
    Qt.Key.Key_6: "6",
    Qt.Key.Key_7: "7",
    Qt.Key.Key_8: "8",
    Qt.Key.Key_9: "9",
    Qt.Key.Key_Colon: ":",
    Qt.Key.Key_Semicolon: ";",
    Qt.Key.Key_Less: "<",
    Qt.Key.Key_Equal: "=",
    Qt.Key.Key_Greater: ">",
    Qt.Key.Key_Question: "?",
    Qt.Key.Key_At: "@",
    Qt.Key.Key_A: "A",
    Qt.Key.Key_B: "B",
    Qt.Key.Key_C: "C",
    Qt.Key.Key_D: "D",
    Qt.Key.Key_E: "E",
    Qt.Key.Key_F: "F",
    Qt.Key.Key_G: "G",
    Qt.Key.Key_H: "H",
    Qt.Key.Key_I: "I",
    Qt.Key.Key_J: "J",
    Qt.Key.Key_K: "K",
    Qt.Key.Key_L: "L",
    Qt.Key.Key_M: "M",
    Qt.Key.Key_N: "N",
    Qt.Key.Key_O: "O",
    Qt.Key.Key_P: "P",
    Qt.Key.Key_Q: "Q",
    Qt.Key.Key_R: "R",
    Qt.Key.Key_S: "S",
    Qt.Key.Key_T: "T",
    Qt.Key.Key_U: "U",
    Qt.Key.Key_V: "V",
    Qt.Key.Key_W: "W",
    Qt.Key.Key_X: "X",
    Qt.Key.Key_Y: "Y",
    Qt.Key.Key_Z: "Z",
    Qt.Key.Key_BracketLeft: "[",
    Qt.Key.Key_Backslash: "\\",
    Qt.Key.Key_BracketRight: "]",
    Qt.Key.Key_AsciiCircum: "^",
    Qt.Key.Key_Underscore: "_",
    Qt.Key.Key_QuoteLeft: "`",
    Qt.Key.Key_BraceLeft: "{",
    Qt.Key.Key_Bar: "|",
    Qt.Key.Key_BraceRight: "}",
    Qt.Key.Key_AsciiTilde: "~"
}


class KeyUtils:
    @staticmethod
    def get_key_description(key) -> str:
        if key in full_key_map:
            return full_key_map[key]
        else:
            return "Unknown"

    @staticmethod
    def get_key_enum(key) -> Qt.Key:
        for k, v in full_key_map.items():
            if v == key:
                return k
        return Qt.Key.Key_unknown


